### ISSUE TITLE
ld stage of installation

### ISSUE THREAD

**Issue by pkravchuk** [davidsd/sdpb#1]
Hi,

I am not sure if this is generic, but I had the following issue when using your makefile: when linking the final target, some symbols from gmp are unresolved, apparently due to ordering of the libs when invoking g++ for $(RESULT). Solved by adding $(LIBS) to the end of the command for $(RESULT). 

I rarely work in linux so I am not sure if this is a problem with my configuration. 

As a side comment, in case someone tries to build this under cygwin -- boost detects cygwin and defines BOOST_WINDOWS_API instead of BOOST_POSIX_API. This makes boost::filesystem::path use wchar_t instead of char_t, which makes it incompatible with tinyxml2. 

And thanks for writing and publishing this solver!

**Comment by davidsd** [comment]
Hi, thanks for opening this issue. I don't know much about these things, so I'll leave the issue here for now -- we'll see if the same change helps anyone else and if so, I'll implement it.

**Comment by pkravchuk** [comment]
I managed to build sdpb under cygwin, so if anyone attempts to do this: This required editing XMLDocument.LoadFile to accept wchar_t* string as filename, converting it to multi-byte string with wcstombs and then passing it to fopen (this is not guaranteed to work on files with non-ascii characters in path, I guess); I also did the same to SaveFile, not sure if it is required. It seems to be the simplest solution. Moreover, one has to add -std=c++0x compilation key in makefile, as well as do the above mentioned modification with $(LIBS). Also, -lgmpxx had to come before -lgmp (since it is the former which depends on the latter) for things to work.

**Comment by davidsd** [comment]
Cool! If you make a cygwin-ready fork of sdpb available on github, I'm sure others would appreciate it.

**Comment by davidsd** [comment]
Perhaps making a fork is too much to ask, but if you have time, would you mind writing step-by-step instructions so I can add them to the Readme? I've made the changes with $(LIBS), -lgmpxx, and -std=c++0x in the Makefile already.

**Comment by pkravchuk** [comment]
Hi,

Sorry for late reply, I was very busy lately. Yeah, sure, I can try to make the instructions. I was actually considering making a fork, but I thought that it would be inconvenient in case you update your code. So I was planning to make a patch which one can apply to your sources. Also I hope to try and make it work under minigw or some other more native Windows environment.

**Comment by davidsd** [comment]
That sounds great. You're right that a patch would probably be better. Would you use CPP to make the tinyxml2 modifications apply only on Windows?

**Comment by pkravchuk** [comment]
Hi, sorry for the extremely long silence. I finally took time and (it seems) figured out the least painful way to get it running on Windows. It involves adding a line to parse.cpp (#ifdef kind of thing, so should not influence other platforms). I submitted a pull request. I have some installation instructions sketched, where would you like me to send them?

**Comment by davidsd** [comment]
You could edit Readme.md and make a pull request, or just post the instructions here and I'll add them.

**Comment by pkravchuk** [comment]
I've just added the instructions to the forked Readme.md. These appear to be rather lengthy, I was wondering if I should make it a separate file? Also, do you have any suggestions how to improve those (perhaps they are too/not sufficiently detailed)?

**Comment by davidsd** [comment]
Thanks for the detailed instructions -- they're a huge help! I split off the installation instructions into their own file, so I think length is not an issue.
