### ISSUE TITLE
Realistic optimization test

### ISSUE THREAD

**Issue by vasdommes** [davidsd/sdpb#104]
Something similar to #103?

**Comment by davidsd** [comment]
I created an optimization test: it's "SingletScalar_cT_test_nmax6" in https://gitlab.com/davidsd/scalars-3d/-/blob/master/src/Projects/Scalars3d/SingletScalar2020.hs?ref_type=heads . You should be able to change `remoteCompute` to `remoteComputeKeepFiles` and grab the json files as before.
