### ISSUE TITLE
Issue with installing on OS X El Capitan 10.11.3

### ISSUE THREAD

**Issue by Martiphy** [davidsd/sdpb#11]
When following your instructions in Install.md for OS X everything works fine until the last step, i.e. compiling the sdpb executable. When compiling I get the following error

`ld: library not found for -lrt`

Apparently it is not a new feature, but simply removing -lrt from the Makefile as suggested in  [https://github.com/davidsd/sdpb/pull/10](url) doesn't work for me. Indeed I get the error

`ld: symbol(s) not found for architecture x86_64`

Could you help me with that? 

Thanks a lot,
Best regards
Martina Cornagliotto

**Comment by davidsd** [comment]
Hi, thanks for opening this issue. I have to apologize that for family reasons I won't have time to work on it for a while. Sorry installing SDPB on OS X is so much work. If you have access to a Linux server in the meantime, that is generally much easier to deal with.

**Comment by Martiphy** [comment]
Hi,
Thanks a lot for your answer, I'll probably work on a Linux server for a
while.
Sorry for the bother.
best,
Martina

2016-06-15 19:39 GMT+02:00 David Simmons-Duffin <notifications@github.com>:

**Comment by davidsd** [comment]
Hi Martina,

Yuji Tachikawa just dramatically simplified the OS X installation process. Install.md has been updated with his instructions. Hopefully they'll work for you!

Best,
David

**Comment by Martiphy** [comment]
Hi David,
Thanks a lot, now it's working perfectly!
Best,
Martina

2016-07-08 23:57 GMT+02:00 David Simmons-Duffin <notifications@github.com>:

**Comment by davidsd** [comment]
Great!
