### ISSUE TITLE
Doesn't build on ubuntu-14.04.5

### ISSUE THREAD

**Issue by spikebike** [davidsd/sdpb#15]
I had to replace:
#include &lt;boost/filesystem.hpp&gt;

With:
#define BOOST_NO_CXX11_SCOPED_ENUMS
#include &lt;boost/filesystem.hpp&gt;
#undef BOOST_NO_CXX11_SCOPED_ENUMS

In 5-6 files to get it to build.  I'll make a pull request to fix this if interested.

**Comment by davidsd** [comment]
Thanks for noticing this! `#define/#undef BOOST_NO_CXX11_SCOPED_ENUMS` seems like an unfortunate thing to have to sprinkle the code with. Is this working around a bug in some version of boost/filesystem.hpp?

**Comment by spikebike** [comment]
On 10/26/2016 08:16 PM, David Simmons-Duffin wrote:
> Thanks for noticing this! |#define/#undef BOOST_NO_CXX11_SCOPED_ENUMS|
> seems like an unfortunate thing to have to sprinkle the code with. Is
> this working around a bug in some version of boost/filesystem.hpp?

Not sure it was a bug, just figured gcc 4.8.4 (default compiler in
ubuntu-14.04) just didn't have a 100% feature complete C++11
implementation.  So the boost folks added the define to be compatible
either way.

I suspect various other OSs like RHEL/CentOS have similar or older
compilers.

**Comment by davidsd** [comment]
Ok, thanks. A pull request would be much appreciated if you have time.

**Comment by spikebike** [comment]
On 10/27/2016 10:49 AM, David Simmons-Duffin wrote:
> Ok, thanks. A pull request would be much appreciated if you have time.

Sure, happy to, done.
