### ISSUE TITLE
--ntasks vs. --procsPerNode

### ISSUE THREAD

**Issue by cpherzog** [davidsd/sdpb#155]
I was trying to do some benchmarking with sdpb and I issued a command like the following

srun --oversubscribe --nodes=1 --ntasks=64 --cpus-per-task=1 --exact --mem=96000M sdpb --procsPerNode=8 <more options>

and the code ran almost identically (about 2 hours of wall time) to the following command

srun --oversubscribe --nodes=1 --ntasks=64 --cpus-per-task=1 --exact --mem=96000M sdpb --procsPerNode=64 <more options>

I was wondering if the --ntasks option over rides the --procsPerNode option in sdpb?

(For some background, I'm working on a cluster where one can only reserve a whole node at a time, so it's then up to the user to structure jobs to take best advantage of the node.  This is the ARCHER2 computer up in Edinburgh.)

Best,
Chris

**Comment by vasdommes** [comment]
Hi Chris,

These options can be a bit confusing indeed.

MPI job distribution on a cluster is always defined by `srun` arguments, e.g. `--nodes=1 --ntasks=64 --cpus-per-task=1`.

`--procsPerNode` is merely a hint to sdpb, which should always be set to to `(ntasks / nodes)`.
It is used for distributing SDP blocks among the CPUs. For example, a big block can be shared among all CPUs on a node, but it will never be shared among different nodes.

In principle, we can determine `procsPerNode` automatically from our code. Thus, we are planning to remove this option, see #141.

**Comment by cpherzog** [comment]
Makes sense.  Thank you.
