### ISSUE TITLE
An option to write sdp to directory instead of zip archive

### ISSUE THREAD

**Issue by vasdommes** [davidsd/sdpb#177]
For large problems, writing block files to sdp.zip is a bottleneck in sdp2input/pvm2sdp, see plots in #176.
It is done by a single process and cannot be parallelized.

The purpose of writing to zip archive instead of plain directory is to prevent `running out of inodes` error on some filesystems.

If this limit is not a problem and if time of writing sdp.zip is important (e.g. in Skydive, where one may call `sdp2input` after each several iterations of SDPB solver), it will be better to write to a directory. We can add e.g. an option `--zip=false`.
(NB: don't forget to validate all file sizes after writing!)

**Comment by davidsd** [comment]
Might there be some other kind of archive format besides zip that can be written to in parallel?

**Comment by vasdommes** [comment]
- [x] #183
