### ISSUE TITLE
gives error with libgmp.so.10 when trying to run executable(CentOS 6.5)

### ISSUE THREAD

**Issue by spraharsh** [davidsd/sdpb#21]
I'm currently trying to install locally on a server without root access. The code compiled without showing any obvious errors but trying to run the compiled executable leads to issues. a make test gives
`[praharsh@chepcs1 sdpb]$ make test
./sdpb -s test.xml --noFinalCheckpoint
./sdpb: error while loading shared libraries: libgmp.so.10: cannot open shared object file: No such file or directory
make: *** [test] Error 127
`
For reference this is what my makefile looks like 

`BASEDIR` := $(HOME)
GMPINCLUDEDIR   = /home/praharsh/lib/include
BOOSTINCLUDEDIR = /home/praharsh/lib/include/boost
LIBDIR          = /home/praharsh/lib/lib`
and the contents of my /home/praharsh/lib/lib contain libgmp.so.10 as clear from the running ls there. Is there any way I can figure out where this error is coming from?

**Comment by davidsd** [comment]
Can you try adding /home/praharsh/lib/lib to your LD_LIBRARY_PATH?

**Comment by spraharsh** [comment]
Thanks It works right now. I did not know the difference between PATH and LD_LIBRARY_PATH.
