### ISSUE TITLE
installing elemental on a cluster complains about missing valgrind.h

### ISSUE THREAD

**Issue by cpherzog** [davidsd/sdpb#224]
I am trying to install elemental on the COSMA8 cluster in Durham and having a lot of trouble.  I was able to do it about a year ago, but something has changed, and the instructions I used no longer work.  

I load the modules 

> module load gnu_comp/10.2.0
> module load cmake/3.25.1
> module load openmpi/4.1.1
> module load openblas/0.3.6  
> module load python/3.10.12
> module load metis/5.1.0-64bit
> module load valgrind/202206

(That I need to load metis and valgrind is new from last year.)

I get a clone from gitlab

> git clone https://gitlab.com/bootstrapcollaboration/elemental.git

Then I make a build directory inside the new elemental directory

> cd elemental
> mkdir -p build
> cd build

cmake does not seem to recognize the mpfr library in LD_LIBRARY_PATH or the include directories in CPATH or C_INCLUDE_PATH, and so I need to type

> cmake .. -DCMAKE_CXX_COMPILER=mpicxx -DCMAKE_C_COMPILER=mpicc -DCMAKE_INSTALL_PREFIX=$MYLIB/elemental/install -DMPFR_INCLUDES=$MYLIB/mpfr/include -DMPFR_LIBRARIES=$MYLIB/mpfr/lib/libmpfr.so

to get the compiler to see my installation of mpfr.  This command produces some warnings and failed tests but otherwise seems to work.  I'm not sure whether to be concerned about them.   The most serious seems to be

> CMake Warning (dev) at cmake/detect/MPI.cmake:11 (find_package):
>   Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
>   Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
>   command to set the policy and suppress this warning.
> 
>   Environment variable MPI_ROOT is set to:
> 
>     /cosma/local/openmpi/gnu_10.2.0/4.1.1
> 
>   For compatibility, CMake is ignoring the variable.
> Call Stack (most recent call first):
>   CMakeLists.txt:402 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.

Then I type make and it fails, despite having loaded a valgrind module:

> make

produces

> [  0%] Built target El_config
> [  0%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/blas/odcpy.c.o
> [  0%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/blas/odscal.c.o
> [  1%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/blas/odswap.c.o
> [  1%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/core/counter.c.o
> [  1%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/core/queue.c.o
> [  1%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/core/rrr.c.o
> [  1%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/core/tasks.c.o
> [  2%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/ode2.c.o
> [  2%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odebz.c.o
> [  2%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odev2.c.o
> [  2%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odnan.c.o
> [  2%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odneg.c.o
> [  3%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odnst.c.o
> [  3%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odr1v.c.o
> [  3%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrnv.c.o
> [  3%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrra.c.o
> [  3%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrb.c.o
> [  4%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrc.c.o
> [  4%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrd.c.o
> [  4%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrre.c.o
> [  4%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrf.c.o
> [  4%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrj.c.o
> [  5%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrk.c.o
> [  5%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrr.c.o
> [  5%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odrrv.c.o
> [  5%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odruv.c.o
> [  5%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odset.c.o
> [  6%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsnan.c.o
> [  6%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsq2.c.o
> [  6%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsq3.c.o
> [  6%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsq4.c.o
> [  6%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsq5.c.o
> [  7%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsq6.c.o
> [  7%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odsrt.c.o
> [  7%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odssq.c.o
> [  7%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/odstmr.c.o
> [  7%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/oerbla.c.o
> [  8%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/lapack/olsame.c.o
> [  8%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/plarre.c.o
> [  8%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/plarrv.c.o
> [  8%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/pmrrr.c.o
> [  8%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/process_c_task.c.o
> [  9%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/process_r_task.c.o
> [  9%] Building C object external/pmrrr/CMakeFiles/pmrrr.dir/src/process_s_task.c.o
> [  9%] Linking C shared library libpmrrr.so
> [  9%] Built target pmrrr
> [  9%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_1.c.o
> [ 10%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_2.c.o
> [ 10%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_aat.c.o
> [ 10%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_control.c.o
> [ 10%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_defaults.c.o
> [ 10%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_dump.c.o
> [ 11%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_info.c.o
> [ 11%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_order.c.o
> [ 11%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_post_tree.c.o
> [ 11%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_postorder.c.o
> [ 11%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_preprocess.c.o
> [ 12%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/amd/amd_valid.c.o
> [ 12%] Building C object external/suite_sparse/CMakeFiles/ElSuiteSparse.dir/src/config.c.o
> [ 12%] Linking C shared library libElSuiteSparse.so
> [ 12%] Built target ElSuiteSparse
> [ 12%] Building CXX object CMakeFiles/El.dir/src/blas_like/blocksizes.cpp.o
> In file included from /cosma8/data/dp328/dc-herz2/library/elemental/elemental/include/El/core.hpp:234,
>                  from /cosma8/data/dp328/dc-herz2/library/elemental/elemental/include/El-lite.hpp:13,
>                  from /cosma8/data/dp328/dc-herz2/library/elemental/elemental/src/blas_like/blocksizes.cpp:9:
> /cosma8/data/dp328/dc-herz2/library/elemental/elemental/include/El/core/imports/valgrind.hpp:14:11: fatal error: valgrind/valgrind.h: No such file or directory
>    14 | # include <valgrind/valgrind.h>
>       |           ^~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make[2]: *** [CMakeFiles/El.dir/src/blas_like/blocksizes.cpp.o] Error 1
> make[1]: *** [CMakeFiles/El.dir/all] Error 2
> make: *** [all] Error 2
>

**Comment by cpherzog** [comment]
I was able to resolve the issue by installing a private copy of valgrind and adding the include directory to CPATH before calling make:  export CPATH=/path/to/valgrind/include:$CPATH

**Comment by vasdommes** [comment]
> CMake Warning (dev) at cmake/detect/MPI.cmake:11 (find_package):
Policy CMP0074 is not set: find_package uses _ROOT variables.
Run "cmake --help-policy CMP0074" for policy details. Use the cmake_policy
command to set the policy and suppress this warning.
>
> Environment variable MPI_ROOT is set to:
>
> ```
> /cosma/local/openmpi/gnu_10.2.0/4.1.1
> ```
> 
> For compatibility, CMake is ignoring the variable.

I think we can ignore this warning - Elemental's CMake configuration is never using the variable `MPI_ROOT` anyway.

**Comment by cpherzog** [comment]
Thanks.  This makes sense.  I may take advantage of your suggestions instead of loading a private copy of valgrind as apparently the standard cosma8 accounts come with a quota for the number of files of 200k and my installation of sdpb with all its dependencies is already in excess of 100k files.

**Comment by vasdommes** [comment]
Note that if your problems contain many SDP blocks, you may also want to call `pmp2sdp` with `--zip` flag (it works slower, but puts all SDP blocks into a single zip archive instead of writing two files per block)
https://github.com/davidsd/sdpb/blob/master/docs/Usage.md#running-out-of-inodes-error
