### ISSUE TITLE
Flint version and missing nmod.h

### ISSUE THREAD

**Issue by bharathr98** [davidsd/sdpb#234]
In the recent change where FLINT and BLAS were added as dependencies, there is a use of `nmod.h` from FLINT in ⬇️
https://github.com/davidsd/sdpb/blob/32afe5da7b15ae6a0a1e16d3b3f097e0da987a0c/src/sdp_solve/SDP_Solver/run/bigint_syrk/fmpz/fmpz_mul_blas_util.hxx#L9

Most older versions of FLINT do not have this header. Instead, the header was originally `nmod_vec.h`, which was later split into `nmod.h` and `nmod_vec.h`. This change was introduced in v2.8.5 (presumably, not explicitly mentioned in the [changelog](https://flintlib.org/doc/history.html), but it can be seen in the PR https://github.com/flintlib/flint/pull/1041)

The simplest fix would be to document this in the `Install.md` file. However I would personally request a different solution, since the UniGE cluster only has v2.7.1 available.

**Comment by vasdommes** [comment]
Will the following work with FLINT 2.7.1?
```
#if __FLINT_RELEASE >= 20805
#include <flint/nmod.h>
#else
#include <flint/nmod_vec.h>
#endif
```
