### ISSUE TITLE
1x1 vs 2x2 systems

### ISSUE THREAD

**Issue by shachrazad** [davidsd/sdpb#29]
If I have a working boostrap system for which the polynomials V=(V_1(x),....V_s(x)) are 1x1 matrices, if seems to me that I should be able to replace them by 2x2 matrices W=(W_1(x),....,W_s(x)) with
W_i(x)={{V_i(x),0},{0,0}}
(0 are vectors with the same size as V_i)

After all, 
alpha.V=alpha_1 V_1(x)+....+alpha_s V_s(x) is >=0 iff  
alpha.W=alpha_1 W_1(x)+....+alpha_s W_s(x) is positive semi-definite.

The normalization vector should be able to stay the same. 

Yet, it does not work. In the example provided "Bootstrap2dExample.m", it just gives
"Segmentation fault (core dumped)". In my code that I am working on, sdpb accepts the input, but gives nonsense.

Why is that?

**Comment by cbehan** [comment]
This file adds superfluous zeros and seems to do what you want. The larger dualErrorThreshold is there to get around the fact that "jumps" take much longer to appear in the 2x2 case.

[Bootstrap2dExample.m.gz](https://github.com/davidsd/sdpb/files/1595007/Bootstrap2dExample.m.gz)

**Comment by shachrazad** [comment]
Thanks a lot! Changing "dualErrorThreshold" worked wonders.

**Comment by davidsd** [comment]
Thanks, Connor!
