### ISSUE TITLE
Followed Mac OS X Instructions, still getting `Undefined symbols for architecture x86_64`

### ISSUE THREAD

**Issue by matonski** [davidsd/sdpb#3]
I posted a question [here](http://stackoverflow.com/questions/28959190/undefined-symbols-compiling-in-mac-os-x-with-boost-gmp-and-openmp) at stackoverflow. Even with the `--enable-cxx` option when I configure GMP, I still get `Undefined symbols for architecture x86_64`.

**Comment by davidsd** [comment]
I modified/updated the instructions in Readme.md. Try them out and let me know if they work for you.

**Comment by matonski** [comment]
Great! It works! Thank you very much!
