### ISSUE TITLE
Some file names cause problems on case-preserving but case-insensitive file systems

### ISSUE THREAD

**Issue by yujitach** [davidsd/sdpb#34]
The two files

https://github.com/davidsd/sdpb/blob/master/src/sdpb/solve/SDP_Solver/run/compute_primal_residues_and_error_p.cxx

and

https://github.com/davidsd/sdpb/blob/master/src/sdpb/solve/SDP_Solver/run/compute_primal_residues_and_error_P.cxx

are only distinguished by the case of the last letter, P or p. This causes a lot of headaches when compiling, on the default file systems on Windows or Mac, which are case-preserving but case-insensitive. (There might be other pairs of files like this.)

This problem can be dealt with by using a file system different from the default on Windows or Mac, but it would be nicer if you do not use two file names distinguished only by the case of the letters.

I would have been happy to prepare a pull request on my side, but I would presume that @wlandry and @davidsd  would have their own opinion on the naming of the files. So I’m raising the issue here first.

**Comment by wlandry** [comment]
Fixed in commit d9b76e4

**Comment by yujitach** [comment]
Thank you very much!
