### ISSUE TITLE
documents of the format of the input directory

### ISSUE THREAD

**Issue by selpoG** [davidsd/sdpb#37]
Now `sdpb` needs input file `sample.xml` to be converted into directory `sample` by `pvm2sdp`.
The format of `sample.xml` is described in [SDPB-Manual.pdf](https://github.com/davidsd/sdpb/blob/master/docs/SDPB-Manual.pdf) or [arXiv:1502.02033](http://arxiv.org/abs/1502.02033), but **no documents for the format of directory `sample` are given**.
If the format is fixed, one can generate directory `sample` directly.

I read source of `pvm2sdp` and conjectured following format (which was successful in generating working input directory).
I think this conjecture is not so wrong, but there should be documents in `sdpb` repository, which would help developers of `PyCFTBoot`, `cboot` or other new wrappers in the future.

### put vector `v` (`N` elements)
```
N
v[0]
...
v[N-1]
```

### put matrix `M` (`r` rows, `c` columns)
```
r c
M[0,0]
...
M[0,c-1]
...
M[r-1,0]
...
M[r-1,c-1]
```

### `blocks.0`
Let `v_I`, `v_m`, `v_d`, `v_s` be a vector of length `J` and for `j=0,...,J-1`, `v_I[j]=j`, `v_m[j]=m_{j+1}`, `v_d[j]=d_{j+1}` and `v_s[j]=(d_{j+1}+1)m_{j+1}(m_{j+1}+1)/2`.
Let `q_r`, `q_c` be a vector of length `2J` and for `j=0,...,J-1`, `q_r[2j]=(floor(d_{j+1}/2)+1)*m_{j+1}`, `q_r[2j+1]=(floor((d_{j+1}-1)/2)+1)*m_{j+1}`, `q_c[2j]=q_c[2j+1]=(d_{j+1}+1)*m_{j+1}`.
```
1
put v_I
put v_m
put v_d
put v_s
put q_r
put q_c
```

### `bilinear_bases.0`
For `j=0,...,J-1`, let `qe_{j+1}` be a matrix of `floor(d_{j+1}/2)+1` rows and `d_{j+1}+1` columns and its element in `m`-th row, `k`-th column (`m,k>=0`) is `sqrt(s_k^{(j+1)})q_m^{(j+1)}(x_k^{(j+1)})`.
For `j=0,...,J-1`, let `qo_{j+1}` be a matrix of `floor((d_{j+1}-1)/2)+1` rows and `d_{j+1}+1` columns and its element in `m`-th row, `k`-th column (`m,k>=0`) is `sqrt(s_k^{(j+1)}x_k^{(j+1)})q_m^{(j+1)}(x_k^{(j+1)})`.
```
J
put qe_1
put qo_1
...
put qe_J
put qo_J
```

### `objectives`
Let `b` be a vector of length `N` and for `n=0,...,N-1`, `b[n]=b_{n+1}`.
```
b_0
put b
```

### for `j=0,...,J-1`, `primal_objective_c.j`
Let `schur=(d_{j+1}+1)m_{j+1}(m_{j+1}+1)/2`.
Let `c_j` be a vector of length `schur` and for `p=0,...,schur-1`, `c_j[p]=s_k^{(j+1)}P_{j+1,r+1,s+1}^0(x_k^{(j+1)}`.
`(r,s,k)` (`0<=s<=r<m_{j+1}` and `0<=k<=d_{j+1}`) corresponds to an index `p` of `c_j`, which is arranged in lexicographical order of `(r,s,k)`.
```
put c_j
```

### for `j=0,...,J-1`, `free_var_matrix.j`
Let `schur=(d_{j+1}+1)m_{j+1}(m_{j+1}+1)/2`.
Let `B_j` be a matrix of `schur` rows and `N` columns and for `p=0,...,schur-1`, `n=0,...,N-1`, `B_j[p,n]=-s_k^{(j+1)}P_{j+1,r+1,s+1}^{n+1}(x_k^{(j+1)}`.
```
put B_j
```

**Comment by wlandry** [comment]
I think these descriptions of the formats are mostly correct.  The only thing I might add is that the `blocks.*` files can span multiple files, not just one file.  That is useful when generating these files in parallel.
I continue to work on optimizations.  In principle, these optimizations could change the format of these files.  For example, they are currently text, but it might be better to make them binary?  I do not think so, but these considerations make me hesitant to encourage others to use them as an output form.
The XML format, on the other hand, is fully supported.  Are you running into problems that might be solved by writing these files directly?  I have made a number of recent improvements to `pvm2sdp` to reduce memory use.

**Comment by selpoG** [comment]
I am developing a new C++ wrapper for SDPB and noticed that the format for `free_var_matrix.j` and `primal_objective_c.j` only requires evaluated elements `P_{j+1,r+1,s+1}^{n+1}(x_k^{(j+1)}`, not explicit coefficients and this property is very crucial in my wrapper.

This is the reason why I want documents, but there could be another workaround:

`pvm2sdp` takes an optional argument `--with-values`, and if `--with-values` is set, a polynomial `f(x)` is represented in XML file by following format.
```XML
<polynomialEvaluation>
  <value>f(x_0)</value>
  ...
  <value>f(x_d)</value>
</polynomialEvaluation>
```

Of course, I can recover coefficients from evaluation by polynomial interpolation, but it is "ill-conditioned at high degree" and not a natural solution (furthermore, very redundant; evaluate and recover coefficients in my wrapper and evaluate in pvm2sdp).

**Comment by wlandry** [comment]
For what you are doing, I agree that you want to directly write values.  Most of what pvm2sdp does is interpolate polynomials. I do not think it would be good to add a `--with-values` option, since it would be bypassing most of what pvm2sdp is doing.
As far as I can tell, you have successfully figured out the format.  Is there anything else that you need documentation for?  As I said, I do not have any plans to change the format, but I am hesitant to make a guarantee.  I can guarantee that if I do change the format, I will increase the version number and note it in the changelog.
Since you are writing a C++ wrapper, you could also use the `libsdp_convert.a` library bundled with SDPB.  Instead of using the default constructor for `Dual_Constraint_Group`, you would create it with your own logic.  Then you can use the included routines to write the input files.  It would make your code more directly coupled with SDPB, which may or may not be OK.
