### ISSUE TITLE
Test file sdp2input_test.m does not describe an SDP solvable by SDPB

### ISSUE THREAD

**Issue by clawrie1729** [davidsd/sdpb#38]
After a fresh install of SDPB (v2.2.0) and the modified elemental library (v0.88) the following sequence of commands, as described in Usage.md, 
```
  sdp2input --precision=1024 --input=test/sdp2input_test.m --output=sdp2input_test
```
and 
```
  sdpb --precision=1024 --procsPerNode=1 -s sdp2input_test
```
yields an error message
```
  A was not numerically HPD: 82 128 -2.94329e-286
```
This is an error coming from inside elemental when it finds that the matrix which it is attempting to decompose is not Hermitian positive definite. 

This appears to be the elemental version of the MPACK error that was described in Issue #28, which occurs when there are flat directions in the SDP, and thus the matrix is degenerate. For other input files that are generated ourselves this error pattern appears when there are flat directions ('too many zeroes') in the SDP and after removing them then running sdp2input and SDPB produces the expected results.

**Comment by wlandry** [comment]
The files ``sdp2input_test.m``, ``sdp2input_split1.m``, ``sdp2input_split2.m``, and ``sdp2input_split.nsv`` are smoke tests for ``sdp2input``'s handling of multiple input files.  So we only check that the output of ``sdp2input -i sdp2input.nsv`` and ``sdp2input -i sdp2input_test.m`` give the same result.  Ideally, we could run that result through ``sdpb``, but that is not necessary for what this test is trying to test.  If you have a better example, I would be willing to include it.

**Comment by clawrie1729** [comment]
Thanks for the clarification! This alleviates any concerns that I had that such an 'error' indicates a subtle failure somewhere in my build.
