### ISSUE TITLE
Format of SDP files for sdp2input

### ISSUE THREAD

**Issue by florentbaume** [davidsd/sdpb#40]
We have created two scripts, one in python and one in Mathematica, to test the OPE-maximisation bootstrap for four identical scalars in 4D. 

The python script dumps the result in a `.m` file in the `SDP[obj, norm, pols]` format described in the manual. Converting to input with `sdp2input` raises no errors, but `SDPB` itself returns a max complementarity exit code. We compared the SDP produced by Python with our Mathematica implementation and found it was strictly the same. The Mathematica implementation finds the expected primal-dual solution. 

I was surprised that importing the SDP in Mathematica and directly re-exporting it, that is running only
``` 
mySDP = Import[“testPython.m”];
Export[“testPython2mma.m”, mySDP];
````
the new SDP `testPython2mma.m` leads to the primal-dual solution we expect (the same as the one produced directly by the Mathematica implementation).

The only difference I can see between the two SDPs is that Mathematica adds precisions after the numbers, e.g. ``1.0000... -> 1`306``.  I took a quick look at the source code of sdp2input, and as far as I understand this added information is stripped off when reading the file.

Is there a particular format beyond what is described in the manual that the SDP must respect? 

The log for both runs can be found [here](https://pastebin.com/AEGMx59w) and the SDPs [here](https://github.com/florentbaume/sdpTesting).

**Comment by wlandry** [comment]
Looking at parse_number.cxx, if the precision is not there, then the parser will not find the exponent correctly.  If you are writing the file yourself, you can add a dummy precision. For example, 6.022`100*^23.

**Comment by clawrie1729** [comment]
In `parse_number.cxx` the precision seems to be only required if there is an exponent. In the SDP linked in `testPython.m` above all of the numbers are of the form `\d+\.?\d*`, without an exponent or precision. These should to be parsed correctly by parse_number. 

This issue then seems to come from some other, unknown, formatting requirement of sdp2input.

**Comment by wlandry** [comment]
It is a bug in the polynomial parsing code.  Let me work on a fix.  Thanks.

**Comment by wlandry** [comment]
I just pushed commit #8574444cd546752e99f2159b346618a54aecf840 which should fix this.  When running your two inputs, I get bitwise identical output directories.
