### ISSUE TITLE
Error when parsing mathematica files

### ISSUE THREAD

**Issue by marioalexis84** [davidsd/sdpb#41]
Hi.
I build SDPB on Debian Buster successfully. However, tests on *.m files in mathematica directory return, e.g. for Bootstrap2dExample.m, the following error:

`alexis@debian:~/Descargas/sdpb-source$ ./build/sdp2input --precision=1024 --input=mathematica/Bootstrap2dExample.m --output=$HOME/test`
`Error: Error when parsing mathematica/Bootstrap2dExample.m: mpf_set_str`
`--------------------------------------------------------------------------`
`MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.`
`
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.`
`--------------------------------------------------------------------------`

I tested the *.xml files in test directory using build/pvm2sdp and build/sdbp, and they run ok as well as the script run_test.sh.

Thanks.

**Comment by wlandry** [comment]
The files in the `mathematica/` directory are scripts for generating inputs using pure Mathematica.  They are not test inputs.  All of the test inputs for the C++ code are in `test/`.

However, the error that you are getting is rather unhelpful.  That should be improved.

**Comment by wlandry** [comment]
I have improved the error message for this case.  When I run

    ./build/sdp2input --precision=1024 --input=mathematica/Bootstrap2dExample.m -o foo

I get

```
Error: Error when parsing mathematica/Bootstrap2dExample.m: Invalid sequence: 'pSDP['.  Is this an SDP file?
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
