### ISSUE TITLE
Custom C++ Flags

### ISSUE THREAD

**Issue by definelicht** [davidsd/sdpb#43]
Is there a way to pass additional flags to the C++ compiler (analogous to `-DCMAKE_CXX_FLAGS`) when building SDPB without modifying `wscript`? I cannot find any such option in `./waf --help`.

Apologies if this is a standard waf feature that I missed - I've never seen or used this build system before.

(Context: we want to inject `-pg` for profiling purposes.)

**Comment by wlandry** [comment]
You can prepend CXXFLAGS when configuring.  So you probably want

    CXXFLAGS='-pg' LINKFLAGS='-pg' ./waf configure ...

To verify, build with `-v`

    ./waf -v

**Comment by definelicht** [comment]
Thank you!
