### ISSUE TITLE
Perhaps add a bit of input validation to sdp2input

### ISSUE THREAD

**Issue by pkravchuk** [davidsd/sdpb#45]
Currently, if one accidentally provides a prefactor with positive poles, `sdp2input` will crash (not for all choices of positive poles) with "Integer division by 0". This is very confusing: in reality this is actually how the square root behaves on negative numbers in `gmp`. The error occurs in line 31 of `sample_bilinear_basis.cxx`, called from line 73 of `Dual_Constraint_Group.cxx`. The reason is that some `sample_scalings` may be negative if some of the poles are positive.

Since positive poles are mathematically meaningless, and messing up relative shifts of these poles is super-easy for the user (I've done this at least twice), it could be helpful to validate the input by checking that all poles are non-positive (zeros are fine).

**Comment by wlandry** [comment]
Done 4c89e69
