### ISSUE TITLE
input file back to XML

### ISSUE THREAD

**Issue by florentbaume** [davidsd/sdpb#46]
I am generating SDPs in the Mathematica format via a Python script and then create the SDPB input file with `sdp2input`. However I want to use [spectrum-extraction](https://gitlab.com/bootstrapcollaboration/spectrum-extraction) on the output, so I need an XML.

While I am aware that `SDPB.m` can convert a `.m` to an XML file, we do not have access to a Mathematica license on the cluster, and `sdp2input` is moreover lightning fast compared to Mathematica. It also has additional advantage of bypassing the need to compute the bilinear bases and samples on our end.

I'm trying to write a parser doing the reverse. Is there a straightforward way to convert the SDPB input format back to an XML? I have looked at the documentation but I couldn't figure out what structure they were following.

**Comment by wlandry** [comment]
No, there is no straightforward way.  There are a number of interpolations that occur during the translation from SDP to input, so I am not sure that it is even possible.

You are not the first person having problems with spectrum extraction, so implementing a proper spectrum extraction tool is already on my TODO list.  I do not have an ETA for that.

**Comment by wlandry** [comment]
Closing this, since going back to the original XML is not feasible.  The spectrum extraction tool is being tracked in issue #48.
