### ISSUE TITLE
Feature request: Termination when stuck after hotstarting, i.e. excessively small P- and D-step

### ISSUE THREAD

**Issue by Marten-Reehorst** [davidsd/sdpb#61]
Are feature requests welcome here? When hot-starting sometimes SDPB gets stuck. When this happens the P-step and D-step become excessively small (e.g. respectively 5.17e-81 and 1.01e-85  within 50 steps). Also beta grows excessively large (2.72e+29). It would be useful if we could terminate based on these parameter values, so that we can restart without a checkpoint. As far as I am aware we cannot do this at the moment.

(There might also be fancy ways to get "unstuck", but this very simple feature would already mitigate most of the problem.)

**Comment by wlandry** [comment]
How many iterations does SDPB take when everything is working normally?  The usual solution to SDPB getting stuck is to set `--maxIterations`.

In general, I am somewhat hesitant to add another option and stopping condition.  SDPB already has many, many options, and it can sometimes be difficult to understand how they all interact.

**Comment by Marten-Reehorst** [comment]
I do exactly that and terminate with maxIterations. The problem is of course that I definitely do not want to terminate a legitimate run that way. That means that I have to take maxIterations to be say 2 or 3 times the usual number of iterations (say without checkpoint because sometime I have to run without checkpoint). Perhaps this is slightly too big a safety margin but I don't want to cause additional confusion by terminating a legit run in which case the restart might again take long. So for every "failed hot-start" actually takes me 2 or 3 full SDPB runs just in order to be able to terminate and know that I have to restart without a checkpoint. On the other hand by looking at the progress I can tell basically within 10 iterations that it is stuck by looking at P-step, D-step and beta. This effect really hurts performance almost completely eliminating the advantage gained by hot-starting.

I am using hot-starting for optimization tasks (Navigator method: https://arxiv.org/abs/2104.09518) so I am encountering getting "stuck" much more often than when using "feasibility-mode". Again there are probably ways to do better, for example not starting from the final check point of the previous point but starting from an intermediate one. This requires some effort and thought though to determine the optimal checkpoint to continue from and until then terminating based on P-step, D-step and beta would be a very simple and efficient solution.

I of course do not want to minimize the effort such a change would take but why would there be a huge interaction with other parts of the code when simply terminating when some threshold is reached in one of these quantities. 

Example run (two tries with checkpoint followed by a successful one without it):
[0.520159427156_1.73895353083_1.04734454632_May26_01h31m25s.sdpb.txt](https://github.com/davidsd/sdpb/files/6548512/0.520159427156_1.73895353083_1.04734454632_May26_01h31m25s.sdpb.txt)

**Comment by wlandry** [comment]
It looks like a run starting from scratch takes about 170 iterations.  When you are hot-starting with a checkpoint, how many iterations does a typical successful run take?

Also, the problem is not the effort to implement the change.  It is really not difficult.  The problem is the increased complexity presented to the user.

**Comment by Marten-Reehorst** [comment]
The gain from hot-starting differs from task to task. I would have to analyze more carefully to see the average gain. But for a task 
like I shared above that would take 170 iterations it goes down to for example 70 iterations. That is, if the hot-start is "successful". When it is stuck I currently lose 500 iterations to find out that it is stuck. So if that happens in say 1 in 10 tasks it almost undoes the (otherwise significant) gain from hot-starting.

I would think that most users wouldn't mind an extra optional argument that they can just ignore when they don't need it.

**Comment by wlandry** [comment]
It is a bit surprising that hot starting only reduces it to 70 iterations.  In any event, I will add an option to stop it early.

**Comment by wlandry** [comment]
I have added `--minPrimalStep` and `--minDualStep` in commit 687bb1a.

**Comment by davidsd** [comment]
I guess it's only internal terminology, but it is a bit funny to use
the term "MinPrimalStepExceeded" when the primal step is actually
*less* than the min primal step. Maybe MinPrimalStepViolated?

**Comment by wlandry** [comment]
Changed it to PrimalStepTooSmall
