### ISSUE TITLE
approx_objective

### ISSUE THREAD

**Issue by Marten-Reehorst** [davidsd/sdpb#62]
It is great to see that approx_objective is now available. 

I have a few questions and comments about it.

Typo: In the usage `newSDP` should be `newSdp`. 

Also what is the exact purpose of the `writeSolverState`? When can/should this state be reused? For each different SDP that I am perturbing from? So say I am perturbing an SDP to N different perturbed SDP', i.e. changing N variables should it be reused for the N-1 following runs? Or can it be reused much more, say for all SDPs of the same form (same number of vectors and order of polynomials) but completely different parameter values?

(It might also be nice to include somewhere that the input format for SDPB has changed and is no longer compatible with the old version. Or is this written somewhere and did I miss it.)

**Comment by wlandry** [comment]
> It is great to see that approx_objective is now available.

It is not quite fully released.  I certainly appreciate feedback at this point.

> Typo: In the usage newSDP should be newSdp.

Fixed.  Thanks.

> Also what is the exact purpose of the writeSolverState? When can/should this state be reused? For each different SDP that I am perturbing from? So say I am perturbing an SDP to N different perturbed SDP', i.e. changing N variables should it be reused for the N-1 following runs? Or can it be reused much more, say for all SDPs of the same form (same number of vectors and order of polynomials) but completely different parameter values?

I reworded that section to:

Setting up the solver can take a long time.  If you have an SDP that
you have perturbed in many different directions, and for logistical
reasons you need to run `approx_objective` separately for each one,
you can save time by saving the solver state with the option
`--writeSolverState`.  To that end, you can also run
`approx_objective` without any new SDP's, only saving the solver
state.


> (It might also be nice to include somewhere that the input format for SDPB has changed and is no longer compatible with the old version. Or is this written somewhere and did I miss it.)

That will be a prominent part of the release notes.
