### ISSUE TITLE
Suppressing block distribution when there are lots of blocks

### ISSUE THREAD

**Issue by davidsd** [davidsd/sdpb#63]
By default, SDPB prints the distribution of blocks between different cores after the timing run. When there are a large number of constraints, this can take up a lot of space in log files. Maybe we could suppress this output when there are a lot of blocks, unless the user sets a high verbosity level?

**Comment by wlandry** [comment]
I think I want to always remove it unless verbosity=2. It was only useful long ago as a debugging aid.

**Comment by davidsd** [comment]
Sounds good to me.

**Comment by wlandry** [comment]
Fixed in commit 0cb1398.
