### ISSUE TITLE
EPFL Fidis and Helvetios compilation failure

### ISSUE THREAD

**Issue by jmarucha** [davidsd/sdpb#68]
Following [installation instructions](https://github.com/davidsd/sdpb/blob/master/Install.md) along with (now obsolete) [site notes](https://github.com/davidsd/sdpb/blob/master/docs/site_installs/EPFL.org).

### Configuration log

```sh
./waf configure --prefix=/home/marucha/.local-sdpb --mpfr-dir=/home/marucha/.local-sdpb --elemental-dir=/home/marucha/.local-sdpb --rapidjson-dir=/home/marucha/.local-sdpb --libarchive-dir=/home/marucha/.local-sdpb --gmpxx-dir=/home/marucha/.local-sdpb
```
and resulting [config.log](https://pastebin.com/CkheaDzw)

### Build log

```sh
 ./waf build -vvv 2>stderr.txt 1>stdout.txt
 ```
 with resulting
 - [stdout](https://pastebin.com/dQjAPF0h)
 - [stderr](https://pastebin.com/EeT80qzG)
 
 ### Software stack
 - RHEL 7.6 with kernel version 3.10.0-957.78.2.el7.x86_64
 - Site packages:
   - gcc 8.4.0
   - openblas 0.3.10
   - **mvapich2** 2.3.4
   - boost 1.73.0
   - cmake 3.16.5 & python 3.7.7 (probably not relevant)
 - Compiled packages
    - gmp-6.2.1 (compiled with `--enable-cxx`)
    - mpfr-4.1.0
    - qd-2.3.23
    - libarchive-v3.6.1
    - rapidjson-1.1.0
    - [bootstrapcollaboration fork of elemental](https://gitlab.com/bootstrapcollaboration/elemental/-/tree/cc51ddb0f33a467fbf580989d9951620ff2a7877)

 ### Hardware
 
 2 x Intel Xeon Gold 6410 (2 x 18c, HT disabled)
 
 ```sh
 cat /proc/cpuinfo
 ```
 
 ```
 ...
 processor       : 35
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz
stepping        : 4
microcode       : 0x2006c0a
cpu MHz         : 2300.000
cache size      : 25344 KB
physical id     : 1
siblings        : 18
core id         : 27
cpu cores       : 18
apicid          : 118
initial apicid  : 118
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 invpcid_single intel_ppin intel_pt ssbd mba ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke md_clear spec_ctrl intel_stibp flush_l1d arch_capabilities
bogomips        : 4604.62
clflush size    : 64
cache_alignment : 64
address sizes   : 46 bits physical, 48 bits virtual
power management:
```

### Afterwords

Honestly, I've never seen GCC *just crashing* before, without mentioning what's roughly wrong with the code. Diagnosing and fixing stuff like that is way beyond my C++ skills and I'd love to learn what went wrong.

**Comment by wlandry** [comment]
Can you work around this by using a different version of gcc?

**Comment by jmarucha** [comment]
I get roughly the same errors with gcc 9.3.0

I tried icpc and intel-mpi, however that was not able to compile GNU MP.

**Comment by wlandry** [comment]
You are getting internal compiler errors with gcc 9.3.0?  Is it on the same file: precompute.cxx?

**Comment by jmarucha** [comment]
These errors happen on multiple files - it's quite random which will cause the failure first if the parallel compilation (as default) happens

**Comment by wlandry** [comment]
You can serialize waf by running it as `waf -j 1`.

**Comment by jmarucha** [comment]
Today I figured out it was not on SDPB's side (neither GCC side)
These errors were due to spotty availability of module folders and the errors I was getting were just broken IO pipes. 
Changing `./waf` to `srun ./waf` seems to get rid of these problems. Thanks for your assistance.
PR #69  descibes the build process.
