### ISSUE TITLE
Assertion failure when loading checkpoint with Boost 1.58

### ISSUE THREAD

**Issue by davidsd** [davidsd/sdpb#7]
Andy Stergiou says:

> I'm writing to you regarding a possible bug in sdpb compiled with boost 1.58. Everything works well until I need to restart a job from a ck file. When I try to do that, I get the following message:
> 
> ```
> sdpb: src/Matrix.cpp:211: void choleskyDecomposition(Matrix&, Matrix&): Assertion `L.rows == dim' failed.
> ```
> 
> There is no problem with the xml file. On the same machine, if I compile sdpb using boost 1.55 and run sdpb on the same xml file this problem is not encountered.

**Comment by davidsd** [comment]
Is the checkpoint file created with the same version of Boost as you're using the load the file?

**Comment by andstergiou** [comment]
Yes.

**Comment by davidsd** [comment]
This is not relevant for the new version of SDPB, which has completely different installation requirements.
