### ISSUE TITLE
Binary input for sdpb

### ISSUE THREAD

**Issue by vasdommes** [davidsd/sdpb#79]
Currently JSON is used. Input file can be several GB, reading it in sdpb is slow (see also #78).
Binary format is more compact (by a factor `~ 8/log2(10) ~ 2.4` ), thus reducing IO costs.

We can add this format and let the user to decide which one to use.

**Comment by vasdommes** [comment]
We can use the same `sdp.zip` archive structure, but instead of `block_XXX.json` write `block_XXX.bin`

**Comment by vasdommes** [comment]
Actual difference between text and binary representations of BigFloat is `~1.70x` for precision=512, `~1.99x` for precision=1024, and `~2.18x` for precision=2048.

**Comment by pkravchuk** [comment]
I guess the would also be a speedup because you don't need to parse the text representation
